### ISSUE TITLE
Is that a new locator problem??

### ISSUE THREAD

**Issue by Mregy1** [nssharmaofficial/reddit-hole#5]
I tried today to run the App and got this error:
"Launching browser...
Opening Reddit...
Logging into Reddit...
Navigating to Reddit thread...
Traceback (most recent call last):
  File "C:\Users\m_ess\Downloads\Compressed\reddit-hole-main\reddit-hole-main\main.py", line 201, in <module>
    main()
  File "C:\Users\m_ess\Downloads\Compressed\reddit-hole-main\reddit-hole-main\main.py", line 133, in main
    reddit.get_screenshots_of_reddit_posts(reddit_thread=thread,
  File "C:\Users\m_ess\Downloads\Compressed\reddit-hole-main\reddit-hole-main\utils\reddit.py", line 197, in get_screenshots_of_reddit_posts
    location = page.locator('shreddit-post[class*="block"]').bounding_box()
  File "C:\Users\m_ess\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\sync_api\_generated.py", line 14782, in bounding_box
    self._sync(self._impl_obj.bounding_box(timeout=timeout))
  File "C:\Users\m_ess\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_sync_base.py", line 115, in _sync
    return task.result()
  File "C:\Users\m_ess\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_locator.py", line 127, in bounding_box
    return await self._with_element(
  File "C:\Users\m_ess\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_locator.py", line 108, in _with_element
    handle = await self.element_handle(timeout=timeout)
  File "C:\Users\m_ess\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_locator.py", line 311, in element_handle
    handle = await self._frame.wait_for_selector(
  File "C:\Users\m_ess\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_frame.py", line 323, in wait_for_selector
    await self._channel.send("waitForSelector", locals_to_params(locals()))
  File "C:\Users\m_ess\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py", line 59, in send
    return await self._connection.wrap_api_call(
  File "C:\Users\m_ess\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py", line 514, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
playwright._impl._errors.TimeoutError: Locator.bounding_box: Timeout 30000ms exceeded.
Call log:
waiting for locator("shreddit-post[class*=\"block\"]")"

Can you help fixing this error??

**Comment by nssharmaofficial** [comment]
It is working for me. Have you tried it then again? Sometimes it can happen because of bad connections. Do you use Windows or Linux?

**Comment by Mregy1** [comment]
Surprisingly it worked now! I've just tried. Yesterday i tried several times even with a VPN and it showed me the above error message.

**Comment by Mregy1** [comment]
Is that always a connection issue?

I tried it again now and didn't work. I am using windows and here is what I got:

"Saved:  ./assets/temp/1fefn71/mp3/title.mp3
Saved:  ./assets/temp/1fefn71/png/fancytitle.png
10 comments are chosen
Launching browser...
Opening Reddit...
Logging into Reddit...
Navigating to Reddit thread...
Saved:  ./assets/temp/1fefn71/png/title.png
Saved:  ./assets/temp/1fefn71/png/0.png
Traceback (most recent call last):
  File "C:\Users\m_ess\Downloads\Compressed\reddit-hole-main\reddit-hole-main\main.py", line 201, in <module>
    main()
  File "C:\Users\m_ess\Downloads\Compressed\reddit-hole-main\reddit-hole-main\main.py", line 133, in main
    reddit.get_screenshots_of_reddit_posts(reddit_thread=thread,
  File "C:\Users\m_ess\Downloads\Compressed\reddit-hole-main\reddit-hole-main\utils\reddit.py", line 211, in get_screenshots_of_reddit_posts
    page.locator("button[aria-controls=\"comment-children\"]").first.click()
  File "C:\Users\m_ess\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\sync_api\_generated.py", line 14929, in click
    self._sync(
  File "C:\Users\m_ess\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_sync_base.py", line 115, in _sync
    return task.result()
  File "C:\Users\m_ess\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_locator.py", line 156, in click
    return await self._frame.click(self._selector, strict=True, **params)
  File "C:\Users\m_ess\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_frame.py", line 488, in click
    await self._channel.send("click", locals_to_params(locals()))
  File "C:\Users\m_ess\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py", line 59, in send
    return await self._connection.wrap_api_call(
  File "C:\Users\m_ess\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py", line 514, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
playwright._impl._errors.TimeoutError: Locator.click: Timeout 30000ms exceeded.
Call log:
waiting for locator("button[aria-controls=\"comment-children\"]").first"

**Comment by nssharmaofficial** [comment]
Yes, I am almost certain that it is only connection issues.

**Comment by Mregy1** [comment]
But it started to save the first two screenshots then stopped as shown above! Even restarted my router and changed my ip address and still got the same message.

**Comment by nssharmaofficial** [comment]
When it sometimes works and sometimes not, there is most probably a problem with the internet, there is nothing much that I can do about that.

**Comment by Mregy1** [comment]
Sure. Thanks for your time.
