### ISSUE TITLE
error waiting for locator("button[aria-controls=\"comment-children\"]")

### ISSUE THREAD

**Issue by bagherip** [nssharmaofficial/reddit-hole#7]
This is the command I run:

(vmaker-env) PS C:\Users\Lenovo\Documents\redditvideomaker\reddit-hole-main> python main.py

I get the following error after running the command. It seems like reddit changed againd the locators?

Comments mode is on for subreddit: redditdev
Version 7.7.1 of praw is outdated. Version 7.8.1 was released Friday October 25, 2024.
Bot logged in to Reddit successfully!
Chosen thread: Software engineering at Reddit  -- Score: 8
Saved:  ./assets/temp/1ggy48a/png/fancytitle.png
3 comments are chosen
Launching browser...
Opening Reddit...
Logging into Reddit...
Navigating to Reddit thread...
Saved:  ./assets/temp/1ggy48a/png/title.png
Traceback (most recent call last):
  File "C:\Users\Lenovo\Documents\redditvideomaker\reddit-hole-main\main.py", line 201, in <module>
    main()
  File "C:\Users\Lenovo\Documents\redditvideomaker\reddit-hole-main\main.py", line 133, in main
    reddit.get_screenshots_of_reddit_posts(reddit_thread=thread,
  File "C:\Users\Lenovo\Documents\redditvideomaker\reddit-hole-main\utils\reddit.py", line 211, in get_screenshots_of_reddit_posts      
    page.locator("button[aria-controls=\"comment-children\"]").first.click()
  File "C:\Users\Lenovo\Documents\redditvideomaker\vmaker-env\lib\site-packages\playwright\sync_api\_generated.py", line 14929, in click
    self._sync(
  File "C:\Users\Lenovo\Documents\redditvideomaker\vmaker-env\lib\site-packages\playwright\_impl\_sync_base.py", line 115, in _sync     
    return task.result()
  File "C:\Users\Lenovo\Documents\redditvideomaker\vmaker-env\lib\site-packages\playwright\_impl\_locator.py", line 156, in click       
    return await self._frame.click(self._selector, strict=True, **params)
  File "C:\Users\Lenovo\Documents\redditvideomaker\vmaker-env\lib\site-packages\playwright\_impl\_frame.py", line 488, in click
    await self._channel.send("click", locals_to_params(locals()))
  File "C:\Users\Lenovo\Documents\redditvideomaker\vmaker-env\lib\site-packages\playwright\_impl\_connection.py", line 59, in send
    return await self._connection.wrap_api_call(
  File "C:\Users\Lenovo\Documents\redditvideomaker\vmaker-env\lib\site-packages\playwright\_impl\_connection.py", line 514, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
playwright._impl._errors.TimeoutError: Locator.click: Timeout 30000ms exceeded.
Call log:
waiting for locator("button[aria-controls=\"comment-children\"]").first

**Comment by peppinl** [comment]
I have the same problem. It happens only on popular subreddits like AmItheAsshole and confession. Somehow there is a time-out at top 5 comments. If I change that to 4 then everything works perfectly. But I can't find any logging as to why there is a time-out. And trying the same subreddit quickly after the error is not working either, so can't say that it is a bad internet connection.

**Comment by diegorccp** [comment]
Same problem for me :C
